feat(01-building blocks):added workflow file

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -11,9 +11,9 @@ jobs :
   echo-goodbye:
      runs-on: ubuntu-latest
      steps:
-       - name: Successful step
+       - name: Failed Step
          run:  |
-           echo "I will succeed"
-           exit 0
+           echo "I will fail"
+           exit 1
        - name: Say Goodbye
          run: echo "Goodbye" 
